export const dashboardData = {
  metadata: {
    title: "Network Delivery Performance",
    description: "Core logistics KPIs by region and month",
    currency: "USD",
    dateFormat: "YYYY-MM-DD",
    regions: ["West", "Southwest", "Midwest", "Southeast", "Northeast"]
  },
  statusThresholds: {
    delayRate: { goodMax: 0.08, warningMax: 0.15 },
    avgDeliveryDays: { goodMax: 3.0, warningMax: 5.0 },
    routeEfficiency: { goodMin: 0.9, warningMin: 0.8 },
    costPerMile: { goodMax: 2.0, warningMax: 3.0 },
    costPerShipment: { goodMax: 480.0, warningMax: 620.0 }
  },
  shipments: [
    {
      shipment_id: "S-1001",
      order_id: "O-9001",
      region: "West",
      state: "CA",
      city: "Los Angeles",
      route: "LA → Seattle",
      origin: "Los Angeles, CA",
      destination: "Seattle, WA",
      mode: "Truckload",
      ship_date: "2026-01-02",
      delivery_date: "2026-01-05",
      promised_delivery_date: "2026-01-06",
      planned_miles: 1150,
      actual_miles: 1180,
      freight_cost: 2200,
      fuel_cost: 620,
      handling_cost: 180,
      delay_reason: ""
    },
    {
      shipment_id: "S-1002",
      order_id: "O-9002",
      region: "West",
      state: "WA",
      city: "Seattle",
      route: "Seattle → San Diego",
      origin: "Seattle, WA",
      destination: "San Diego, CA",
      mode: "Truckload",
      ship_date: "2026-01-03",
      delivery_date: "2026-01-09",
      promised_delivery_date: "2026-01-07",
      planned_miles: 1250,
      actual_miles: 1400,
      freight_cost: 2500,
      fuel_cost: 710,
      handling_cost: 210,
      delay_reason: "Port congestion"
    },
    {
      shipment_id: "S-1003",
      order_id: "O-9003",
      region: "Southwest",
      state: "TX",
      city: "Dallas",
      route: "Dallas → Phoenix",
      origin: "Dallas, TX",
      destination: "Phoenix, AZ",
      mode: "Truckload",
      ship_date: "2026-01-04",
      delivery_date: "2026-01-06",
      promised_delivery_date: "2026-01-07",
      planned_miles: 1050,
      actual_miles: 1060,
      freight_cost: 1800,
      fuel_cost: 480,
      handling_cost: 140,
      delay_reason: ""
    },
    {
      shipment_id: "S-1004",
      order_id: "O-9004",
      region: "Midwest",
      state: "IL",
      city: "Chicago",
      route: "Chicago → Detroit",
      origin: "Chicago, IL",
      destination: "Detroit, MI",
      mode: "LTL",
      ship_date: "2026-01-05",
      delivery_date: "2026-01-07",
      promised_delivery_date: "2026-01-06",
      planned_miles: 300,
      actual_miles: 320,
      freight_cost: 650,
      fuel_cost: 210,
      handling_cost: 90,
      delay_reason: "Cross dock"
    },
    {
      shipment_id: "S-1005",
      order_id: "O-9005",
      region: "Southeast",
      state: "GA",
      city: "Atlanta",
      route: "Atlanta → Miami",
      origin: "Atlanta, GA",
      destination: "Miami, FL",
      mode: "Truckload",
      ship_date: "2026-01-02",
      delivery_date: "2026-01-04",
      promised_delivery_date: "2026-01-05",
      planned_miles: 660,
      actual_miles: 690,
      freight_cost: 1400,
      fuel_cost: 380,
      handling_cost: 120,
      delay_reason: ""
    },
    {
      shipment_id: "S-1006",
      order_id: "O-9006",
      region: "Southeast",
      state: "FL",
      city: "Miami",
      route: "Miami → Atlanta",
      origin: "Miami, FL",
      destination: "Atlanta, GA",
      mode: "Truckload",
      ship_date: "2026-01-08",
      delivery_date: "2026-01-12",
      promised_delivery_date: "2026-01-10",
      planned_miles: 660,
      actual_miles: 720,
      freight_cost: 1450,
      fuel_cost: 390,
      handling_cost: 120,
      delay_reason: "Storms"
    },
    {
      shipment_id: "S-1007",
      order_id: "O-9007",
      region: "Northeast",
      state: "NY",
      city: "New York",
      route: "NYC → Boston",
      origin: "New York, NY",
      destination: "Boston, MA",
      mode: "LTL",
      ship_date: "2026-01-03",
      delivery_date: "2026-01-05",
      promised_delivery_date: "2026-01-05",
      planned_miles: 220,
      actual_miles: 230,
      freight_cost: 540,
      fuel_cost: 160,
      handling_cost: 70,
      delay_reason: ""
    },
    {
      shipment_id: "S-1008",
      order_id: "O-9008",
      region: "Northeast",
      state: "NJ",
      city: "Newark",
      route: "Newark → Philadelphia",
      origin: "Newark, NJ",
      destination: "Philadelphia, PA",
      mode: "LTL",
      ship_date: "2026-01-06",
      delivery_date: "2026-01-09",
      promised_delivery_date: "2026-01-08",
      planned_miles: 90,
      actual_miles: 110,
      freight_cost: 420,
      fuel_cost: 130,
      handling_cost: 60,
      delay_reason: "Dwell"
    }
  ]
};
